### ISSUE TITLE
Cloth Config3

### ISSUE THREAD

**Issue by moderninity** [Maxmani/lock-on#1]
sorry, I'm trying to delete my on curseforge but the site isn't letting me!

As stated there I downloaded for 1.20.1 but the mod says it requires cloth config v12. There's no Cloth Config v12 for 1.20.1

Fabric Loader output:
`Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: 
Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Cloth Config v11' (cloth-config) 11.0.99, mod 'Cloth Config v11' (cloth-config) 11.1.106 and mod 'Cloth Config v11' (cloth-config) 11.1.106 with mod 'Cloth Config v11' (cloth-config), version 12.0.0 or later.
Unmet dependency listing:
	 - Mod 'Lock On' (lockon) 1.0.0+1.20.2 requires version 12.0.0 or later of mod 'Cloth Config v11' (cloth-config), but only the wrong versions are present: 11.1.106/11.1.106/11.0.99!
	 - Mod 'Statement Vanilla Compatibility Module' (statement_vanilla_compatibility) 1.0.1+1.14.4-1.15.2 requires any version between 1.14.0-0 (inclusive) and 1.16.0-0 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
`

**Comment by Maxmani** [comment]
Ah, yeah I figured this would happen. You can fix this manually by opening the jar archive and editing/removing `"cloth-config2": ">=12.0.0"` under `depends` in the `fabric.mod.json` file. I'll have this fixed soon.

**Comment by Maxmani** [comment]
Fixed in 1.0.1.

**Comment by moderninity** [comment]
Thank you!
