### ISSUE TITLE
Exclude self from entity list

### ISSUE THREAD

**Issue by Entropy159** [Maxmani/lock-on#3]
I've noticed that sometimes my view goes straight down when locking on. I soon figured out it's because I was included in the entity list, so I was tracking myself. This could be a simple fix I think but not too urgent.

**Comment by Maxmani** [comment]
That shouldn't happen, since it already excludes players, but I'll look into it.

**Comment by Entropy159** [comment]
Oh that's right. I forked it to add more entities, should've remembered it was my fault.
If you ever do add support for players then watch out for that. (I fixed it by removing the player from the list)

**Comment by Entropy159** [comment]
Sorry for the inconvenience.
